# Generated by Django 6.0.4 on 2026-04-13 14:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=500)),
                ('language', models.CharField(max_length=100)),
                ('platform_relevance', models.JSONField(blank=True, default=list, help_text='List of platform names where this keyword is effective')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('deprecated', 'Deprecated'), ('candidate', 'Candidate')], default='active', max_length=20)),
                ('shared', models.BooleanField(default=False, help_text='Visible to all projects in the same organization')),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='keywords_added', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='keywords', to='core.keywordcategory')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keywords', to='core.organization')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keywords', to='core.project')),
            ],
            options={
                'ordering': ['-date_added'],
                'constraints': [models.UniqueConstraint(fields=('project', 'term', 'language'), name='unique_keyword_per_project_lang')],
            },
        ),
    ]
