# Generated by Django 6.0.4 on 2026-04-13 14:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('keywords', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_id', models.CharField(editable=False, max_length=50)),
                ('url', models.URLField(blank=True, max_length=2048)),
                ('screenshot', models.ImageField(blank=True, upload_to='screenshots/%Y/%m/')),
                ('date_of_post', models.DateField(blank=True, null=True)),
                ('date_collected', models.DateTimeField(auto_now_add=True)),
                ('location_mentioned', models.CharField(blank=True, max_length=255)),
                ('probable_location', models.CharField(blank=True, max_length=255)),
                ('language', models.CharField(blank=True, max_length=100)),
                ('confidence', models.CharField(blank=True, choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('reviewed', 'Reviewed'), ('flagged', 'Flagged')], default='draft', max_length=20)),
                ('extra_fields', models.JSONField(blank=True, default=dict)),
                ('collected_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents', to=settings.AUTH_USER_MODEL)),
                ('duplicate_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicates', to='incidents.incident')),
                ('keywords_matched', models.ManyToManyField(blank=True, related_name='incidents', to='keywords.keyword')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='core.organization')),
                ('platform', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents', to='core.platform')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='core.project')),
            ],
            options={
                'ordering': ['-date_collected'],
                'constraints': [models.UniqueConstraint(fields=('project', 'record_id'), name='unique_record_id_per_project')],
            },
        ),
    ]
