# Generated by Django 6.0.4 on 2026-04-18 14:18

from django.db import migrations, models


def _backfill(apps, schema_editor):
    from apps.incidents.utils import normalize_url
    Incident = apps.get_model("incidents", "Incident")
    batch = []
    for inc in Incident.objects.only("pk", "url").iterator():
        inc.url_normalized = normalize_url(inc.url)
        batch.append(inc)
        if len(batch) >= 500:
            Incident.objects.bulk_update(batch, ["url_normalized"])
            batch.clear()
    if batch:
        Incident.objects.bulk_update(batch, ["url_normalized"])


def _noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='url_normalized',
            field=models.CharField(blank=True, db_index=True, max_length=2048),
        ),
        migrations.RunPython(_backfill, _noop),
    ]
